services:
  web:
    build: .

    ports:
      - '8000:8000'

    volumes:
      - ./data:/app/data

    env_file:
      - .env

    depends_on:
      - db

  db:
    image: postgres:17

    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
    environment:
      - POSTGRES_USER=Varenik
      - POSTGRES_PASSWORD=Vkusny
      - POSTGRES_DB=vcdb

    ports:
      - "5432:5432"

volumes:
  postgres_data: