apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: vacancies-collector
spec:
  replicas: 2

  selector:
    matchLabels:
      app: app

  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app-container
          image: varenikvkusny/vacancies-collector:1.3
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: app-config

          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD

            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: BOT_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: vacancies-collector
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  selector:
    app: app
  ports:
    - port: 8000
      targetPort: 8000
