apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
  namespace: vacancies-collector
spec:
  selector:
    matchLabels:
      app: bot
  replicas: 1

  template:
    metadata:
      labels:
        app: bot

    spec:
      containers:
        - name: bot-container

          image: varenikvkusny/vacancies-collector:1.3

          command: ["python", "-m", "src.tg_bot.main_bot"]

          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"

          envFrom:
            - configMapRef:
                name: app-config

          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: BOT_TOKEN
