apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: vacancies-collector
spec:
  replicas: 1

  selector:
    matchLabels:
      app: worker

  template:
    metadata:
      labels:
        app: worker

    spec:
      containers:
        - name: worker-container
          image: varenikvkusny/vacancies-collector:1.1
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"

          envFrom:
            - configMapRef:
                name: app-config

          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: RABBITMQ_PASSWORD
