name: Run Python Tests

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            redis:
                image: redis:8-alpine

                options: >-
                    --health-cmd "redis-cli ping"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                
                ports:
                    - 6380:6379

            rabbitmq:
                image: rabbitmq:3-management
                ports:
                - 5672:5672
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Create .env file for tests
              run: |
                echo "TEST_MODE=true" >> .env # Флаг, что мы в тестах
          
                echo "DB_DRIVER=sqlite+aiosqlite" >> .env
                echo "DB_NAME=:memory:" >> .env
                
                echo "REDIS_HOST=localhost" >> .env
                echo "REDIS_PORT=6380" >> .env
                echo "REDIS_DB=1" >> .env

                echo "RABBITMQ_HOST=localhost" >> .env
                echo "RABBITMQ_PORT=5672" >> .env
                echo "RABBITMQ_USER=guest" >> .env
                echo "RABBITMQ_PASSWORD=guest" >> .env

                echo "SECRET_KEY=test_secret_for_ci" >> .env
                echo "ALGORITHM=HS256" >> .env
                echo "ACCESS_TOKEN_EXPIRE_MINUTES=30" >> .env
                echo "BOT_TOKEN=fake_bot_token_for_ci" >> .env
                echo "API_BASE_URL=http://test" >> .env

            - name: Run tests
              run: pytest